---
# tasks file for localize
- name: Read distro specific variables.
  ansible.builtin.include_vars: '{{ ansible_os_family | lower }}.yml'

- name: Install locale sources packages.
  ansible.builtin.package:
    name: '{{ locale_packages }}'
    state: present

# Community module locale_gen does not work on EL
- name: Check if locale exists.
  ansible.builtin.shell:
    cmd: locale -a | grep -i {{ config_system_locale | regex_replace('-', '') | quote }}
  register: found_locale
  changed_when: no
  failed_when: no

- name: Set localedef parameters.
  ansible.builtin.set_fact:
    _i: "{{ config_system_locale | regex_replace('(.+)\\..*', '\\1') | quote }}"
    _f: "{{ config_system_locale | regex_replace('.+\\.(.*)', '\\1') | quote }}"

- name: Create locale.
  ansible.builtin.command:
    cmd: localedef -i {{ _i }} -f {{ _f }} {{ config_system_locale | quote }}
  when: not ansible_check_mode and found_locale.rc != 0

- name: Get current locale and language configuration.
  ansible.builtin.command:
    cmd: localectl status
  register: locale_status
  changed_when: false

- name: Parse 'LANG' from current locale and language configuration.
  ansible.builtin.set_fact:
    locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | default(['n/a'], true) | first }}"

- name: Configure locale.
  ansible.builtin.command:
    cmd: localectl set-locale LANG={{ config_system_locale }}
  when: locale_lang != config_system_locale
